// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0--rc2
// source: proto/taskList.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskList_AddTask_FullMethodName    = "/proto.TaskList/AddTask"
	TaskList_DoneTask_FullMethodName   = "/proto.TaskList/DoneTask"
	TaskList_ListTasks_FullMethodName  = "/proto.TaskList/ListTasks"
	TaskList_DeleteTask_FullMethodName = "/proto.TaskList/DeleteTask"
)

// TaskListClient is the client API for TaskList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskListClient interface {
	AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error)
	DoneTask(ctx context.Context, in *IdTask, opts ...grpc.CallOption) (*Void, error)
	ListTasks(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Tasks, error)
	DeleteTask(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
}

type taskListClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskListClient(cc grpc.ClientConnInterface) TaskListClient {
	return &taskListClient{cc}
}

func (c *taskListClient) AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TaskList_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListClient) DoneTask(ctx context.Context, in *IdTask, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TaskList_DoneTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListClient) ListTasks(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Tasks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tasks)
	err := c.cc.Invoke(ctx, TaskList_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListClient) DeleteTask(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TaskList_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskListServer is the server API for TaskList service.
// All implementations must embed UnimplementedTaskListServer
// for forward compatibility.
type TaskListServer interface {
	AddTask(context.Context, *Task) (*Void, error)
	DoneTask(context.Context, *IdTask) (*Void, error)
	ListTasks(context.Context, *Void) (*Tasks, error)
	DeleteTask(context.Context, *Void) (*Void, error)
	mustEmbedUnimplementedTaskListServer()
}

// UnimplementedTaskListServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskListServer struct{}

func (UnimplementedTaskListServer) AddTask(context.Context, *Task) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedTaskListServer) DoneTask(context.Context, *IdTask) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoneTask not implemented")
}
func (UnimplementedTaskListServer) ListTasks(context.Context, *Void) (*Tasks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskListServer) DeleteTask(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskListServer) mustEmbedUnimplementedTaskListServer() {}
func (UnimplementedTaskListServer) testEmbeddedByValue()                  {}

// UnsafeTaskListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskListServer will
// result in compilation errors.
type UnsafeTaskListServer interface {
	mustEmbedUnimplementedTaskListServer()
}

func RegisterTaskListServer(s grpc.ServiceRegistrar, srv TaskListServer) {
	// If the following call pancis, it indicates UnimplementedTaskListServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskList_ServiceDesc, srv)
}

func _TaskList_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskListServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskList_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskListServer).AddTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskList_DoneTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskListServer).DoneTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskList_DoneTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskListServer).DoneTask(ctx, req.(*IdTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskList_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskListServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskList_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskListServer).ListTasks(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskList_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskListServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskList_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskListServer).DeleteTask(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskList_ServiceDesc is the grpc.ServiceDesc for TaskList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TaskList",
	HandlerType: (*TaskListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskList_AddTask_Handler,
		},
		{
			MethodName: "DoneTask",
			Handler:    _TaskList_DoneTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskList_ListTasks_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskList_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/taskList.proto",
}
